// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using QuanLyKhoaHoc.Data;

#nullable disable

namespace QuanLyKhoaHoc.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260930194635_SetDecimalPrecision")]
    partial class SetDecimalPrecision
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("QuanLyKhoaHoc.Models.ChuongTrinhDaoTao", b =>
                {
                    b.Property<int>("MaChuongTrinhDaoTao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaChuongTrinhDaoTao"));

                    b.Property<string>("EmailLienHe")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("MoTa")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("TenChuongTrinhDaoTao")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int>("TrangThai")
                        .HasColumnType("int");

                    b.HasKey("MaChuongTrinhDaoTao");

                    b.HasIndex("TenChuongTrinhDaoTao")
                        .IsUnique();

                    b.ToTable("ChuongTrinhDaoTaos");
                });

            modelBuilder.Entity("QuanLyKhoaHoc.Models.HoSoDangKyHoc", b =>
                {
                    b.Property<int>("MaHoSo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaHoSo"));

                    b.Property<string>("GhiChu")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("LyDoDangKy")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("MaHocVien")
                        .HasColumnType("int");

                    b.Property<int>("MaLop")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayNop")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NgayXuLy")
                        .HasColumnType("datetime2");

                    b.Property<string>("NhanXetXetDuyet")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("TrangThai")
                        .HasColumnType("int");

                    b.HasKey("MaHoSo");

                    b.HasIndex("MaHocVien");

                    b.HasIndex("MaLop");

                    b.ToTable("HoSoDangKyHocs");
                });

            modelBuilder.Entity("QuanLyKhoaHoc.Models.HocVien", b =>
                {
                    b.Property<int>("MaHocVien")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaHocVien"));

                    b.Property<string>("DiaChi")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("Email")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("GioiTinh")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<int>("MaTaiKhoan")
                        .HasColumnType("int");

                    b.Property<string>("MucTieuHoc")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime?>("NgaySinh")
                        .HasColumnType("datetime2");

                    b.Property<string>("NgheNghiep")
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("SoDienThoai")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<int>("SoThangDaHoc")
                        .HasColumnType("int");

                    b.Property<bool>("TrangThai")
                        .HasColumnType("bit");

                    b.Property<string>("TrinhDoHienTai")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("MaHocVien");

                    b.HasIndex("MaTaiKhoan")
                        .IsUnique();

                    b.ToTable("HocViens");
                });

            modelBuilder.Entity("QuanLyKhoaHoc.Models.KetQuaXepLop", b =>
                {
                    b.Property<int>("MaKetQuaXepLop")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaKetQuaXepLop"));

                    b.Property<decimal?>("DiemDanhGia")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("DuocXepLop")
                        .HasColumnType("bit");

                    b.Property<int>("MaHoSo")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayCapNhat")
                        .HasColumnType("datetime2");

                    b.Property<string>("NhanXet")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.HasKey("MaKetQuaXepLop");

                    b.HasIndex("MaHoSo")
                        .IsUnique();

                    b.ToTable("KetQuaXepLops");
                });

            modelBuilder.Entity("QuanLyKhoaHoc.Models.LichKiemTraDauVao", b =>
                {
                    b.Property<int>("MaLichKiemTraDauVao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaLichKiemTraDauVao"));

                    b.Property<string>("DiaDiemHoacLienKet")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("GhiChu")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("GiaoVienKiemTra")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("HinhThucKiemTra")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<int>("MaHoSo")
                        .HasColumnType("int");

                    b.Property<DateTime>("ThoiGianBatDau")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ThoiGianKetThuc")
                        .HasColumnType("datetime2");

                    b.Property<int>("TrangThai")
                        .HasColumnType("int");

                    b.HasKey("MaLichKiemTraDauVao");

                    b.HasIndex("MaHoSo");

                    b.ToTable("LichKiemTraDauVaos");
                });

            modelBuilder.Entity("QuanLyKhoaHoc.Models.LopHoc", b =>
                {
                    b.Property<int>("MaLop")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaLop"));

                    b.Property<decimal>("DiemDauVaoToiThieu")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("HanDangKy")
                        .HasColumnType("datetime2");

                    b.Property<int>("MaChuongTrinhDaoTao")
                        .HasColumnType("int");

                    b.Property<string>("MoTaLopHoc")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<DateTime>("NgayBatDauDangKy")
                        .HasColumnType("datetime2");

                    b.Property<int>("SiSoToiDa")
                        .HasColumnType("int");

                    b.Property<string>("TenLop")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<int>("TrangThai")
                        .HasColumnType("int");

                    b.Property<string>("TrinhDoDauVao")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("YeuCauHocVien")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.HasKey("MaLop");

                    b.HasIndex("MaChuongTrinhDaoTao");

                    b.ToTable("LopHocs");
                });

            modelBuilder.Entity("QuanLyKhoaHoc.Models.TaiKhoan", b =>
                {
                    b.Property<int>("MaTaiKhoan")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaTaiKhoan"));

                    b.Property<string>("Email")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("MatKhau")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("TenDangNhap")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("TrangThai")
                        .HasColumnType("int");

                    b.Property<int>("VaiTro")
                        .HasColumnType("int");

                    b.HasKey("MaTaiKhoan");

                    b.HasIndex("TenDangNhap")
                        .IsUnique();

                    b.ToTable("TaiKhoans");
                });

            modelBuilder.Entity("QuanLyKhoaHoc.Models.HoSoDangKyHoc", b =>
                {
                    b.HasOne("QuanLyKhoaHoc.Models.HocVien", "HocVien")
                        .WithMany("HoSos")
                        .HasForeignKey("MaHocVien")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("QuanLyKhoaHoc.Models.LopHoc", "LopHoc")
                        .WithMany("HoSos")
                        .HasForeignKey("MaLop")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("HocVien");

                    b.Navigation("LopHoc");
                });

            modelBuilder.Entity("QuanLyKhoaHoc.Models.HocVien", b =>
                {
                    b.HasOne("QuanLyKhoaHoc.Models.TaiKhoan", "TaiKhoan")
                        .WithOne("HocVien")
                        .HasForeignKey("QuanLyKhoaHoc.Models.HocVien", "MaTaiKhoan")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("TaiKhoan");
                });

            modelBuilder.Entity("QuanLyKhoaHoc.Models.KetQuaXepLop", b =>
                {
                    b.HasOne("QuanLyKhoaHoc.Models.HoSoDangKyHoc", "HoSoDangKyHoc")
                        .WithOne("KetQuaXepLop")
                        .HasForeignKey("QuanLyKhoaHoc.Models.KetQuaXepLop", "MaHoSo")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("HoSoDangKyHoc");
                });

            modelBuilder.Entity("QuanLyKhoaHoc.Models.LichKiemTraDauVao", b =>
                {
                    b.HasOne("QuanLyKhoaHoc.Models.HoSoDangKyHoc", "HoSoDangKyHoc")
                        .WithMany("LichKiemTras")
                        .HasForeignKey("MaHoSo")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("HoSoDangKyHoc");
                });

            modelBuilder.Entity("QuanLyKhoaHoc.Models.LopHoc", b =>
                {
                    b.HasOne("QuanLyKhoaHoc.Models.ChuongTrinhDaoTao", "ChuongTrinhDaoTao")
                        .WithMany("LopHocs")
                        .HasForeignKey("MaChuongTrinhDaoTao")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ChuongTrinhDaoTao");
                });

            modelBuilder.Entity("QuanLyKhoaHoc.Models.ChuongTrinhDaoTao", b =>
                {
                    b.Navigation("LopHocs");
                });

            modelBuilder.Entity("QuanLyKhoaHoc.Models.HoSoDangKyHoc", b =>
                {
                    b.Navigation("KetQuaXepLop");

                    b.Navigation("LichKiemTras");
                });

            modelBuilder.Entity("QuanLyKhoaHoc.Models.HocVien", b =>
                {
                    b.Navigation("HoSos");
                });

            modelBuilder.Entity("QuanLyKhoaHoc.Models.LopHoc", b =>
                {
                    b.Navigation("HoSos");
                });

            modelBuilder.Entity("QuanLyKhoaHoc.Models.TaiKhoan", b =>
                {
                    b.Navigation("HocVien");
                });
#pragma warning restore 612, 618
        }
    }
}
